### ISSUE TITLE
Key Error on text in line 73 of config_and_run.py 

### ISSUE THREAD

**Issue by MohammedMUddin** [theo-go/twitter_selenium_get_tweets#1]
I am not that well versed in Pandas but I wanted to try this code out anyway as all the other scrapers are down. I am getting an error when I use **df['text'].apply(parse_text)**.

**Comment by MohammedMUddin** [comment]
I was able to fix the above replacing the above with this in line 73: **df.all_text.apply(parse_text)**. This is just applying parse_text function to all the elements in the all_text column.

**Comment by theo-go** [comment]
Hey @MohammedMUddin. I just uploaded a new version of the script that will return more tweets since it queries your advanced search(es) every x number of days. Has a couple more explainer comments thruout as well.
