### ISSUE TITLE
Get "Your connection is not private" issue when trying to scrape tweets with sample query

### ISSUE THREAD

**Issue by SachinPendse** [theo-go/twitter_selenium_get_tweets#2]
Hi Theo, 

Thank you so much for this code (along with the detailed explanation on Medium). When I try to run it, I get an error of "Your connection is not private" and the scraper is unable to actually scrape the tweets. Is there some configuration (e.g. telling Google to allow this program to run) that I need to do for the script to work? Thanks again! I've attached a picture of the specific error --- your advice would be much appreciated. 

Sachin

<img width="716" alt="Screen Shot 2020-11-27 at 10 35 54 PM" src="https://user-images.githubusercontent.com/6971883/100493055-3cd12580-3101-11eb-93c9-de65604fb0f7.png">

**Comment by theo-go** [comment]
Looks like an issue that you can fix via Selenium @SachinPendse. Good luck!
https://stackoverflow.com/a/60250587/9738461
