### ISSUE TITLE
Unable to pull all posts from single search query

### ISSUE THREAD

**Issue by wchia-cil** [theo-go/twitter_selenium_get_tweets#3]
Hey Theo, I've tried to run your script using the following configs:

urls = [
    'https://twitter.com/search?q=(from%3Atheregister)']
start_date = '2020-6-1'
end_date = '2020-6-2'

days_between = 1

The scrapper only retrieves 4 tweets, when there are many more - have you come across this error before, if so how did you deal with it? thanks!

**Comment by theo-go** [comment]
Hi @wchia-cil thanks for giving this a go. I haven't pushed any changes to this repo in a while -- I'd recommend using: https://github.com/Altimis/Scweet
